# Generated by Django 4.2.15 on 2024-10-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodestablishment',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='foodestablishment',
            name='preview_photos',
        ),
    ]
