# Generated by Django 4.2.15 on 2024-10-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_foodestablishment_cuisine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='amenities',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='accommodations', to='places.amenity'),
        ),
    ]
