# Generated by Django 4.2.15 on 2024-10-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_building_amenities_accommodation_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('building_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='places.building')),
                ('num_bedrooms', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('kitchen', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('OLD', 'Old')], default='GOOD', max_length=10)),
                ('furniture_condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('USED', 'Used')], default='GOOD', max_length=10)),
                ('lease_term', models.CharField(choices=[('SHORT_TERM', 'Short-term'), ('LONG_TERM', 'Long-term'), ('MONTH_TO_MONTH', 'Month-to-month')], default='LONG_TERM', max_length=20)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.ManyToManyField(blank=True, related_name='rentals', to='places.amenity')),
            ],
            options={
                'abstract': False,
            },
            bases=('places.building',),
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
    ]
