# Generated by Django 4.2.15 on 2024-10-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_rental_delete_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='emergency_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='refrigerator',
            field=models.BooleanField(default=False),
        ),
    ]
