# Generated by Django 4.2.15 on 2024-10-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rental_emergency_exit_rental_refrigerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
