# Generated by Django 4.2.15 on 2024-10-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_rental_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='price_per_night',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
