# Generated by Django 4.2.15 on 2024-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_rental_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('DORMITORY', 'Dormitory'), ('CONDOMINIUM', 'Condominium')], default='APARTMENT', max_length=20),
        ),
    ]
