# Generated by Django 4.2.15 on 2024-10-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_building_latitude_alter_building_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
