# Generated by Django 4.2.15 on 2024-10-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_building_latitude_alter_building_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
