# Generated by Django 4.2.15 on 2024-10-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_photo_alter_userprofile_user'),
        ('places', '0012_building_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='places.rental')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_favorites', to='user_profile.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'rental')},
            },
        ),
        migrations.CreateModel(
            name='FoodEstablishmentFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='places.foodestablishment')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_favorites', to='user_profile.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'food_establishment')},
            },
        ),
    ]
