# Generated by Django 4.2.15 on 2024-10-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_photo_alter_userprofile_user'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0013_rentalfavorite_foodestablishmentfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user_profile', 'content_type', 'object_id')},
        ),
    ]
