# Generated by Django 4.2.15 on 2024-11-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_review_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodestablishment',
            options={'verbose_name': 'Establishment', 'verbose_name_plural': 'Establishments'},
        ),
    ]
