# Generated by Django 4.2.15 on 2024-11-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_alter_foodestablishment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='contact_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='contact_number',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
