# Generated by Django 4.2.15 on 2024-11-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_rental_contact_name_alter_rental_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='building',
            name='contact_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='contact_number',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
