# Generated by Django 4.2.15 on 2024-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_remove_rental_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='contact_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
