# Generated by Django 4.2.15 on 2024-11-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_alter_building_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='available_bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
