# Generated by Django 4.2.15 on 2024-11-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_rental_available_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodestablishment',
            name='is_open_24_hours',
            field=models.BooleanField(default=False),
        ),
    ]
