# Generated by Django 4.2.15 on 2024-09-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_photo_alter_userprofile_user'),
        ('establishment', '0002_alter_businesscategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shop', to='user_profile.userprofile'),
        ),
    ]
