# Generated by Django 4.2.15 on 2024-09-15 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_alter_business_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssubcategory',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='establishment.businesscategory'),
        ),
    ]
