# Generated by Django 4.2.15 on 2024-09-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0005_alter_businesscategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscategory',
            name='map_icon',
        ),
        migrations.AddField(
            model_name='business',
            name='map_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/map/icon/'),
        ),
    ]
